version: '3.3'

services:
  accountservice:
    build: .
    environment:
      PORT: ${PORT:-8089}
    command: run
    restart: always
    ports:
      - ${PORT:-8089}:8089
    expose:
      - ${PORT:-8089}
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: ${COGNITIVE_NETWORK:-bridge}